config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end

  unauthenticated do
    root 'splash#splash', as: :unauthenticated_root
  end

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users
  resources :groups, path: 'categories', only: [:index, :new, :create, :destroy] do
    resources :operations, path: 'transactions', only: [:index, :new, :create, :destroy]
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, :icon, presence: true

  belongs_to :user, foreign_key: 'user_id'
  has_and_belongs_to_many :operations
end

app/models/operation.rb
class Operation < ApplicationRecord
  validates :name, presence: true
  validates :amount, numericality: { only_decimal: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_and_belongs_to_many :groups
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true

  has_many :groups
  has_many :operations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @groups = @user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)
    @group.user = current_user

    if @group.save
      flash[:success] = 'Category created successfully'
      redirect_to groups_path
    else
      flash[:danger] = 'Category could not be created'
      render :new
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    flash[:notice] = 'Category has been successfully deleted'
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @operations = @group.operations
  end

  def new
    @group = Group.find(params[:group_id])
    @operation = Operation.new
  end

  def create
    @group = Group.find(params[:group_id])
    @operation = Operation.new(operation_params)
    @operation.author_id = current_user.id
    @operation.groups << @group

    if @operation.save
      flash[:success] = 'Transaction created successfully'
      redirect_to group_operations_path
    else
      flash[:danger] = 'Transaction could not be created'
    end
  end

  def destroy
    @operation = Operation.find(params[:id])
    @operation.destroy

    flash[:notice] = 'Transaction has been successfully deleted'
    redirect_to group_operations_path
  end

  private

  def operation_params
    params.require(:operation).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def splash; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<section class="main_section">
<%= render 'shared/navbar' %>
<ul class="categories_list">
  <% @groups.each_with_index do |group, index| %>
    <%= link_to group_operations_path(group), class: "card_link" do%>
      <li class="category_item">
        <img src= <%= group.icon %> alt = <%= group.name %> />
        <div class="name_date">
          <p><%= group.name %></p>
          <p class="date_time"><%= group.created_at.strftime("%Y-%m-%d") %></p>
        </div>
        <p><%= group.operations.sum(:amount) %></p>
      </li>
    <% end %>
  <% end %>
</ul>
<div class="btn_div">
  <button class="new_category_btn"><%= link_to 'New Category', new_group_path, class: "new_category_link" %></button>
</div>
</section>

app/views/groups/new.html.erb
<section class="main_section">
<%= render 'shared/navbar' %>

<div class="form_container categories_form">
<%= form_with model: @group, url: groups_path(current_user) do |form| %>
    <div class="field">
      <%= form.label :name, class: "label" %>      
      <%= form.text_field :name, placeholder: 'Enter Category Name*', required: true, class: "input" %>
    </div>

    <div class="field">
      <%= form.label :icon, class: "label" %>
      <%= form.text_field :icon, placeholder: 'Icon URL*', required: true, class: "input" %>
    </div>

    <%= form.submit class: "create_btn" %>
<% end %>
</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://fonts.cdnfonts.com/css/proxima-nova-2" rel="stylesheet">
                
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/operations/index.html.erb
<section class="main_section">
<%= render 'shared/navbar' %>

<div class="total_amount">
  <p>Total: </p>
  <span>Ksh<%= @operations.sum(:amount)%></span>
</div>

<div class="delete_category">
  <%= button_to group_path(@group), method: :delete, data: { turbo_frame: 'groups' }, class: "delete_btn" do %>
  <div class="text_icon">
    <i class="fa-solid fa-trash-can delete_icon"></i>
    <p>Delete Category</p>
  </div>
  <% end %>
</div>

<ul class="categories_list">
  <% @operations.each_with_index do |operation, index| %>
    <li class="category_item">
      <div class="name_section">
        <p><%= operation.name %></p>
        <p class="date_time"><%= operation.created_at.strftime("%Y-%m-%d") %></p>
      </div>
      <div class="amount_section">
        <p><%= operation.amount %></p>
        <div>
          <%= button_to group_operation_path(@group, operation), method: :delete, data: { turbo_frame: "operations" }, class: "delete_btn" do %>
            <i class="fa-solid fa-trash-can delete_icon"></i>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
</ul>

<div class="btn_div new_transaction">
  <button class="new_category_btn"><%= link_to 'New Transaction', new_group_operation_path, class: "new_category_link" %></button>
</div>
</section>

app/views/operations/new.html.erb
<section class="main_section">
<%= render 'shared/navbar' %>

<div class="form_container categories_form">
<%= form_with model: @operation, url: group_operations_path(@group) do |form| %>
  <div class="field">
    <%= form.label :name, class: "label" %><br>
    <%= form.text_field :name, required: true, placeholder: 'Expense Name*', class: "input" %>
  </div>

  <div class="field">
    <%= form.label :amount, class: "label" %><br>
    <%= form.number_field :amount, required: true, placeholder: 'Amount*', class: "input" %>
  </div>

  <%= form.submit "Create Transaction", class: "create_btn" %>
<% end %>
</div>
</section>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <% if controller_name == 'groups' && action_name == 'index' %> 
    <i class="fa-solid fa-bars icon"></i>
  <% elsif controller_name == 'groups' && action_name == 'new' || controller_name == 'operations' && action_name == 'index' %>
    <%= link_to groups_path, class: "login_link" do %>
      <i class="fa-solid fa-arrow-left icon"></i>
    <% end %>
  <% elsif controller_name == 'operations' && action_name == 'new' %>
      <%= link_to group_operations_path, class: "login_link" do %>
        <i class="fa-solid fa-arrow-left icon"></i>
      <% end %>
  <% end %>
  
  <p class="navbar_header">
    <% if controller_name == 'groups' && action_name == 'index' %>
      CATEGORIES
    <% elsif controller_name == 'groups' && action_name == 'new' %>
      NEW CATEGORY
    <% elsif controller_name == 'operations' && action_name == 'index' %>
      <%= @group.name.upcase %>
    <% else controller_name == 'operations' && action_name == 'new' %>
      CREATE TRANSACTION
    <% end %>
  </p>

  <div class="nav_signout">
    <%= link_to 'Sign Out', destroy_user_session_path, data: {
      turbo_method: :delete,
    }, class: "nav_signout_link" %>
    <span><i class="fa-solid fa-arrow-right-from-bracket nav_signout_icon"></i></span>
  </div>
</nav>

app/views/splash/splash.html.erb
<section class="splash_container">
  <h1 class="splash_header">Snapscan</h1>
  <div class="login">
    <button class="login_btn"><%=  link_to "LOG IN", new_user_session_path, class: "login_link" %></button>
  </div>

  <div class="signup">
    <button class="signup_btn"><%= link_to "SIGN UP", new_user_registration_path, class: "signup_link" %></button>
  </div>
</section>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>